environment:
  matrix:

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Debug
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Release
     platform: x64

   - job_name: Windows
     APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
     configuration: Retail
     platform: x64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: debug64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: release64

   - job_name: Linux
     APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2204
     buildcfg: retail64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: debug64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: release64

   - job_name: OSX
     APPVEYOR_BUILD_WORKER_IMAGE: macOS-sonoma
     buildcfg: retail64

shallow_clone: true

install:
- git submodule init
- git submodule update

for:
  
# ======================================
# Windows
# ======================================

  -
    matrix:
      only:
      - job_name: Windows
    
    init:
    - git clone --depth 1 https://github.com/RudjiGames/MTunerInject MTunerInject
    - git clone --depth 1 https://github.com/RudjiGames/build        build
    - git clone --depth 1 https://github.com/RudjiGames/rbase        rbase
    - git clone --depth 1 https://github.com/RudjiGames/rdebug       rdebug
    - git clone --depth 1 https://github.com/RudjiGames/DIA          DIA

    install:
      - build\tools\bin\windows\genie.exe --file=MTunerInject\genie\genie.lua vs2022

    build: ../.build/windows/vs2022/MTunerInject/projects/rqt.sln

# ======================================
# Linux
# ======================================

  -
    matrix:
      only:
      - job_name: Linux

    init:
      - git clone --depth 1 https://github.com/RudjiGames/MTunerInject MTunerInject
      - git clone --depth 1 https://github.com/RudjiGames/build        build
      - git clone --depth 1 https://github.com/RudjiGames/rbase        rbase
      - git clone --depth 1 https://github.com/RudjiGames/rdebug       rdebug
      - git clone --depth 1 https://github.com/bkaradzic/GENie         GENie		# build GENie from source: `GLIBC_2.29' not found
      - cd GENie && make && cd ..

    install:
      - ./GENie/bin/linux/genie --file=MTunerInject/genie/genie.lua --gcc=linux-gcc gmake
  
    build_script:
      - cd ./.build/linux/linux-gcc/MTunerInject/projects/
      - make config=${buildcfg}

# ======================================
# OSX
# ======================================

  -
    matrix:
      only:
      - job_name: OSX

    init:
      - git clone --depth 1 https://github.com/RudjiGames/MTunerInject MTunerInject
      - git clone --depth 1 https://github.com/RudjiGames/build        build
      - git clone --depth 1 https://github.com/RudjiGames/rbase        rbase
      - git clone --depth 1 https://github.com/RudjiGames/rdebug       rdebug
      - git clone --depth 1 https://github.com/bkaradzic/GENie GENie  # build GENie from source: we don't know the target CPU, can't use ARM binary from 'build'
      - cd GENie && make && cd ..
    
    install:
      - ./GENie/bin/darwin/genie --file=MTunerInject/genie/genie.lua --gcc=osx-x64 gmake
    
    build_script:
      - cd ./.build/osx/clang/MTunerInject/projects/
      - make config=${buildcfg}
