language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - clang

before_script:
    - git clone --depth 1 https://github.com/milostosic/build  ../build
    - git clone --depth 1 https://github.com/milostosic/rbase  ../rbase
    - git clone --depth 1 https://github.com/milostosic/rdebug ../rdebug
    - git clone --depth 1 https://github.com/glfw/glfw ../glfw

script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libc6-dev-i386 gcc-5-multilib g++-5-multilib; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libx11-dev libxext-dev libxpm-dev libxrandr-dev libxrender-dev libxcursor-dev libxi-dev libxinerama-dev; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd .. && mkdir glfwbuild && cd glfwbuild && cmake ../glfw && make -j4 && sudo make install && cd ../MTunerInject; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make linux CXX="g++-5" CC="gcc-5"; fi
#    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make osx; fi

branches:
  only:
    - master

notifications:
  email: false

osx_image: xcode9.3

